### ISSUE TITLE
ImportError: cannot import name 'get_moreDA_augmentation'

### ISSUE THREAD

**Issue by epiccc** [dan-gut/DL_models_benchmark#1]
I try to start training the dataset (task 2), I found the following long error, that i couldn't attach here.
In the nnUNet (the latest version), There is no "get_moreDA_augmentation".
----------------------------------------------------
Traceback (most recent call last):
  File "run_training.py", line 24, in <module>
    from nnUNetTrainerV2 import nnUNetTrainerV2
  File "/root/DL_models_benchmark/nnUNet/nnUNetTrainerV2.py", line 23, in <module>
    from nnunet.training.data_augmentation.default_data_augmentation import get_moreDA_augmentation
ImportError: cannot import name 'get_moreDA_augmentation' from 'nnunet.training.data_augmentation.default_data_augmentation' (/root/nnUNet/nnunet/training/data_augmentation/default_data_augmentation.py)

-----------------------------------

Thanks for the help.

**Comment by dan-gut** [comment]
Hi!
Method get_moreDA_augmentation was moved to a different file in one of the nnUNet updates. Now it can be found in file nnunet/training/data_augmentation/data_augmentation_moreDA.py. 
Try changing the import in trainer file (nnUNetTrainerV2.py file, line 23):
`from nnunet.training.data_augmentation.default_data_augmentation import get_moreDA_augmentation`
to
`from nnunet.training.data_augmentation.data_augmentation_moreDA import get_moreDA_augmentation`

**Comment by epiccc** [comment]
Thank you very much for your reply. My issue has been solved.
But there are new issues. 

---------------------------------------
Exception in background worker 0:
 index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 48, in producer
    item = transform(**item)
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/transforms/abstract_transforms.py", line 88, in __call__
    data_dict = t(**data_dict)
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/transforms/spatial_transforms.py", line 346, in __call__
    ret_val = augment_spatial(data, seg, patch_size=patch_size,
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/augmentations/spatial_transformations.py", line 200, in augment_spatial
    seg_result = np.zeros((seg.shape[0], seg.shape[1], patch_size[0], patch_size[1], patch_size[2]),
IndexError: index 1 is out of bounds for axis 0 with size 1
using pin_memory on device 0
Traceback (most recent call last):
  File "run_training.py", line 122, in <module>
    main()
  File "run_training.py", line 110, in main
    trainer.run_training()
  File "/root/DL_models_benchmark/CS2Net/nnCSNetTrainerV2.py", line 437, in run_training
    ret = super().run_training()
  File "/usr/local/lib/python3.8/dist-packages/nnunet/training/network_training/nnUNetTrainer.py", line 317, in run_training
    super(nnUNetTrainer, self).run_training()
  File "/usr/local/lib/python3.8/dist-packages/nnunet/training/network_training/network_trainer.py", line 418, in run_training
    _ = self.tr_gen.next()
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 182, in next
    return self.__next__()
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 206, in __next__
    item = self.__get_next_item()
  File "/usr/local/lib/python3.8/dist-packages/batchgenerators/dataloading/multi_threaded_augmenter.py", line 190, in __get_next_item
    raise RuntimeError("MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of "
RuntimeError: MultiThreadedAugmenter.abort_event was set, something went wrong. Maybe one of your workers crashed. This is not the actual error message! Look further up your stdout to see what caused the error. Please also check whether your RAM was full

**Comment by taborzbislaw** [comment]
Hi,

I am not quite sure, but I think that I got similar error when trying to run nnUNet on CPU.
I suggest that you first run plane nnUNet_train in the same environment as the one in which the error was recorded.

If there is no error when running nnUNet_train, then before using our codes you have first to fix issues related to versions of dependencies.
The code at Daniel's github was prepared for nnUNet  1.6.2, batchgenerators  0.20.1, SimpleITK 1.2.4 - if I remember well these are the most important dependencies. But it does not make sense to install all these old versions of the libraries.

I expect that your goal is to use your own architecture in nnUNet framework.  The most basic way to do that is to copy three files: run_training.py (from nnunet/run), nnUNetTrainerV2.py (from nnunet/training/network_training but other trainers may be used as well), and generic_UNet.py (from nnunet/network_architecture) to some directory, replace all nnunet imports present in these scripts by local imports e.g. instead:
from nnunet.training.network_training.nnUNetTrainer_v2 import nnUNetTrainer_v2
use 
from nnUNetTrainer_v2 import nnUNetTrainer_v2

After you replace all nnunet imports related to the three above files by local ones, you have to do some code editing. In particular, in [line 137 ](https://github.com/MIC-DKFZ/nnUNet/blob/master/nnunet/run/run_training.py#L137) of run_training.py get_default_configuration function is called. In this function the class of trainer is searched for, based on a string passed through the command line. Instead of calling this function, in our versions of run_training.py we hardcoded necessary data e.g.:

    workdir = '/net/archive/groups/plgg_matszym/nnUNet/'
    plans_file = workdir + 'nnUNet_preprocessed/Task001_Hip/nnUNetPlansv2.1_plans_2D.pkl'
    output_folder_name = workdir + 'nnUNet_trained_models/nnUNet/2d/Task001_Hip/MEM_nnUNetTrainerV2__nnUNetPlansv2.1'
    dataset_directory = workdir + 'nnUNet_preprocessed/Task001_Hip'
    batch_dice = True
    stage = 0
    trainer_class = nnUNetTrainerV2

After doing such code edits try to run run_training.py script with appropriate command line arguments e.g.:
python3 run_training.py 3d_fullres nnUNetTrainerV2 Task002_MYTASK FOLD --npz
where e.g. FOLD = 0

When running the code check if your local codes are indeed used. If you manage to run so prepared code, you may try to replace the architecture in generic_UNet.py by your own architecture.
I am afraid that these is no easier way to run your models in nnUNet framework as this framework evolves quite fast and is not very friendly for those who want to do some modifications of the code.

After your models are trained, some work as above will be necessary to run predictions with your own architecture.

Regards,
Zbisław
